[versions]
kotlin = "1.9.10"
# https://androidx.dev/storage/compose-compiler/repository
compose-kotlin-compiler = "1.5.3"
agp = "8.1.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
#kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

[libraries]
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-core = "androidx.core:core-ktx:1.12.0"
androidx-activity = "androidx.activity:activity-ktx:1.8.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.8.0"
androidx-lifecycle-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.3.0"
androidx-dynamicanimation = "androidx.dynamicanimation:dynamicanimation:1.0.0"
androidx-annotation = "androidx.annotation:annotation:1.6.0"
androidx-preference = "androidx.preference:preference-ktx:1.2.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-browser = "androidx.browser:browser:1.5.0"
androidx-window = "androidx.window:window:1.1.0"
google-material = "com.google.android.material:material:1.11.0-alpha03"
androidx-startup = "androidx.startup:startup-runtime:1.1.1"
androidx-compose-bom = "androidx.compose:compose-bom:2023.10.00"

blurhash-android = "io.github.hushenghao:blurhash-android:1.0.1"
viewbinding-delegate = "com.github.kirich1409:viewbindingpropertydelegate-noreflection:1.5.9"
io-coil = "io.coil-kt:coil:2.4.0"
free-reflection = "com.github.tiann:FreeReflection:3.2.0"
squareup-leakcanary = "com.squareup.leakcanary:leakcanary-android-startup:2.12"
nanohttpd = "org.nanohttpd:nanohttpd:2.3.1"

junit = "junit:junit:4.13.2"
androidx-test-core = "androidx.test:core-ktx:1.5.0"
androidx-test-ext = "androidx.test.ext:junit-ktx:1.1.5"
androidx-expresso-core = "androidx.test.espresso:espresso-core:3.5.1"
androidx-expresso-contrib = "androidx.test.espresso:espresso-contrib:3.5.1"
androidx-expresso-intents = "androidx.test.espresso:espresso-intents:3.5.1"
junit-junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[bundles]
android-test = ["androidx-test-core", "androidx-test-ext", "androidx-expresso-core",
    "androidx-expresso-contrib", "androidx-expresso-intents"]
