// Generated by data binding compiler. Do not edit!
package com.j.jOS.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.databinding.Bindable;
import androidx.databinding.DataBindingUtil;
import androidx.databinding.ViewDataBinding;
import com.j.jOS.R;
import java.lang.Deprecated;
import java.lang.Object;

public abstract class ActivityMenuBinding extends ViewDataBinding {
  @NonNull
  public final CardView bh196;

  @NonNull
  public final CoordinatorLayout coordinatorLayout;

  @NonNull
  public final CardView ics;

  @NonNull
  public final ImageView imageView1;

  @NonNull
  public final ImageView imageView11;

  @NonNull
  public final ImageView imageView12;

  @NonNull
  public final ImageView imageView2;

  @NonNull
  public final ImageView imageView3;

  @NonNull
  public final ImageView imageView4;

  @NonNull
  public final ImageView imageView5;

  @NonNull
  public final CardView jf916;

  @NonNull
  public final CardView k;

  @NonNull
  public final CardView l;

  @NonNull
  public final LinearLayout layoutDescription1;

  @NonNull
  public final LinearLayout layoutDescription11;

  @NonNull
  public final LinearLayout layoutDescription12;

  @NonNull
  public final LinearLayout layoutDescription2;

  @NonNull
  public final LinearLayout layoutDescription3;

  @NonNull
  public final LinearLayout layoutDescription4;

  @NonNull
  public final LinearLayout layoutDescription5;

  @NonNull
  public final CardView p;

  @NonNull
  public final CardView q;

  @NonNull
  public final TextView textViewTopHeader;

  @Bindable
  protected String mVersion;

  protected ActivityMenuBinding(Object _bindingComponent, View _root, int _localFieldCount,
      CardView bh196, CoordinatorLayout coordinatorLayout, CardView ics, ImageView imageView1,
      ImageView imageView11, ImageView imageView12, ImageView imageView2, ImageView imageView3,
      ImageView imageView4, ImageView imageView5, CardView jf916, CardView k, CardView l,
      LinearLayout layoutDescription1, LinearLayout layoutDescription11,
      LinearLayout layoutDescription12, LinearLayout layoutDescription2,
      LinearLayout layoutDescription3, LinearLayout layoutDescription4,
      LinearLayout layoutDescription5, CardView p, CardView q, TextView textViewTopHeader) {
    super(_bindingComponent, _root, _localFieldCount);
    this.bh196 = bh196;
    this.coordinatorLayout = coordinatorLayout;
    this.ics = ics;
    this.imageView1 = imageView1;
    this.imageView11 = imageView11;
    this.imageView12 = imageView12;
    this.imageView2 = imageView2;
    this.imageView3 = imageView3;
    this.imageView4 = imageView4;
    this.imageView5 = imageView5;
    this.jf916 = jf916;
    this.k = k;
    this.l = l;
    this.layoutDescription1 = layoutDescription1;
    this.layoutDescription11 = layoutDescription11;
    this.layoutDescription12 = layoutDescription12;
    this.layoutDescription2 = layoutDescription2;
    this.layoutDescription3 = layoutDescription3;
    this.layoutDescription4 = layoutDescription4;
    this.layoutDescription5 = layoutDescription5;
    this.p = p;
    this.q = q;
    this.textViewTopHeader = textViewTopHeader;
  }

  public abstract void setVersion(@Nullable String version);

  @Nullable
  public String getVersion() {
    return mVersion;
  }

  @NonNull
  public static ActivityMenuBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup root, boolean attachToRoot) {
    return inflate(inflater, root, attachToRoot, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.activity_menu, root, attachToRoot, component)
   */
  @NonNull
  @Deprecated
  public static ActivityMenuBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup root, boolean attachToRoot, @Nullable Object component) {
    return ViewDataBinding.<ActivityMenuBinding>inflateInternal(inflater, R.layout.activity_menu, root, attachToRoot, component);
  }

  @NonNull
  public static ActivityMenuBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.inflate(inflater, R.layout.activity_menu, null, false, component)
   */
  @NonNull
  @Deprecated
  public static ActivityMenuBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable Object component) {
    return ViewDataBinding.<ActivityMenuBinding>inflateInternal(inflater, R.layout.activity_menu, null, false, component);
  }

  public static ActivityMenuBinding bind(@NonNull View view) {
    return bind(view, DataBindingUtil.getDefaultComponent());
  }

  /**
   * This method receives DataBindingComponent instance as type Object instead of
   * type DataBindingComponent to avoid causing too many compilation errors if
   * compilation fails for another reason.
   * https://issuetracker.google.com/issues/116541301
   * @Deprecated Use DataBindingUtil.bind(view, component)
   */
  @Deprecated
  public static ActivityMenuBinding bind(@NonNull View view, @Nullable Object component) {
    return (ActivityMenuBinding)bind(component, view, R.layout.activity_menu);
  }
}
