// Generated by view binder compiler. Do not edit!
package com.j.jOS.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.j.jOS.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class AgainAgainBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final TextView pleasexit;

  private AgainAgainBinding(@NonNull FrameLayout rootView, @NonNull TextView pleasexit) {
    this.rootView = rootView;
    this.pleasexit = pleasexit;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static AgainAgainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AgainAgainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.again_again, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AgainAgainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.pleasexit;
      TextView pleasexit = ViewBindings.findChildViewById(rootView, id);
      if (pleasexit == null) {
        break missingId;
      }

      return new AgainAgainBinding((FrameLayout) rootView, pleasexit);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
