// Generated by view binder compiler. Do not edit!
package com.j.jOS.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.j.jOS.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentLockBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final RecyclerView fragmentListwallpapersRecyclerView;

  @NonNull
  public final Button skipLock;

  private FragmentLockBinding(@NonNull LinearLayout rootView,
      @NonNull RecyclerView fragmentListwallpapersRecyclerView, @NonNull Button skipLock) {
    this.rootView = rootView;
    this.fragmentListwallpapersRecyclerView = fragmentListwallpapersRecyclerView;
    this.skipLock = skipLock;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentLockBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentLockBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_lock, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentLockBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.fragment_listwallpapers_recyclerView;
      RecyclerView fragmentListwallpapersRecyclerView = ViewBindings.findChildViewById(rootView, id);
      if (fragmentListwallpapersRecyclerView == null) {
        break missingId;
      }

      id = R.id.skip_lock;
      Button skipLock = ViewBindings.findChildViewById(rootView, id);
      if (skipLock == null) {
        break missingId;
      }

      return new FragmentLockBinding((LinearLayout) rootView, fragmentListwallpapersRecyclerView,
          skipLock);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
