// Generated by view binder compiler. Do not edit!
package com.j.jOS.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.j.jOS.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ItemWallpaperBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final ImageView itemWallpaperImage;

  @NonNull
  public final TextView itemWallpaperTitle;

  private ItemWallpaperBinding(@NonNull CardView rootView, @NonNull ImageView itemWallpaperImage,
      @NonNull TextView itemWallpaperTitle) {
    this.rootView = rootView;
    this.itemWallpaperImage = itemWallpaperImage;
    this.itemWallpaperTitle = itemWallpaperTitle;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemWallpaperBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemWallpaperBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_wallpaper, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemWallpaperBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.item_wallpaper_image;
      ImageView itemWallpaperImage = ViewBindings.findChildViewById(rootView, id);
      if (itemWallpaperImage == null) {
        break missingId;
      }

      id = R.id.item_wallpaper_title;
      TextView itemWallpaperTitle = ViewBindings.findChildViewById(rootView, id);
      if (itemWallpaperTitle == null) {
        break missingId;
      }

      return new ItemWallpaperBinding((CardView) rootView, itemWallpaperImage, itemWallpaperTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
