// Generated by view binder compiler. Do not edit!
package com.j.jOS.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.android_l.egg.LLand;
import com.j.jOS.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class LLlandBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final TextView score;

  @NonNull
  public final TextView welcome;

  @NonNull
  public final LLand world;

  private LLlandBinding(@NonNull FrameLayout rootView, @NonNull TextView score,
      @NonNull TextView welcome, @NonNull LLand world) {
    this.rootView = rootView;
    this.score = score;
    this.welcome = welcome;
    this.world = world;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static LLlandBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static LLlandBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
      boolean attachToParent) {
    View root = inflater.inflate(R.layout.l_lland, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static LLlandBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.score;
      TextView score = ViewBindings.findChildViewById(rootView, id);
      if (score == null) {
        break missingId;
      }

      id = R.id.welcome;
      TextView welcome = ViewBindings.findChildViewById(rootView, id);
      if (welcome == null) {
        break missingId;
      }

      id = R.id.world;
      LLand world = ViewBindings.findChildViewById(rootView, id);
      if (world == null) {
        break missingId;
      }

      return new LLlandBinding((FrameLayout) rootView, score, welcome, world);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
