// Generated by view binder compiler. Do not edit!
package com.j.jOS.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.Toolbar;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.j.jOS.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class SettingsActivityBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Toolbar actionBar;

  @NonNull
  public final FrameLayout contentFrame;

  @NonNull
  public final LinearLayout contentParent;

  private SettingsActivityBinding(@NonNull LinearLayout rootView, @NonNull Toolbar actionBar,
      @NonNull FrameLayout contentFrame, @NonNull LinearLayout contentParent) {
    this.rootView = rootView;
    this.actionBar = actionBar;
    this.contentFrame = contentFrame;
    this.contentParent = contentParent;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static SettingsActivityBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static SettingsActivityBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.settings_activity, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static SettingsActivityBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.action_bar;
      Toolbar actionBar = ViewBindings.findChildViewById(rootView, id);
      if (actionBar == null) {
        break missingId;
      }

      id = R.id.content_frame;
      FrameLayout contentFrame = ViewBindings.findChildViewById(rootView, id);
      if (contentFrame == null) {
        break missingId;
      }

      LinearLayout contentParent = (LinearLayout) rootView;

      return new SettingsActivityBinding((LinearLayout) rootView, actionBar, contentFrame,
          contentParent);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
